### PR TITLE
remove parallel worker code

### PR DESCRIPTION
**Pull request by brettkoonce**
will need to rebuild the associated auto-generated files as well.

### CODE REVIEW

**Comment by jph00** [comment]
@brettkoonce what's the reason for removing that?

**Comment by brettkoonce** [comment]
Ran into this error when running the 08_data_block notebook:

```
error: <Cell 39>:8:71: error: extra argument 'parallelCallCount' in call
    return DataBunch(train: data.train.innerDs.map(parallelCallCount: nWorkers){ DataBatch(xb: tfmItem($0.xb), yb: $0.yb) },
                                                                      ^~~~~~~~
```

Doesn't appear to be matching code anywhere:

https://github.com/fastai/fastai_docs/search?q=parallelCallCount&unscoped_q=parallelCallCount

**Comment by sgugger** [comment]
I had no problem running the notebook with 0.3.1.

**Comment by brettkoonce** [comment]
@sgugger fair enough, have an old checkout!

**Pull request closed without merging**
