### PR TITLE
Migrate 00_load_data to new APIs.

### PR DESCRIPTION
**Pull request by rxwei**

### CODE REVIEW

**Comment by rxwei** [comment]
Am I supposed to save output or no?

**Comment by sgugger** [comment]
As long as you run the script `tools/run-after-git-clone` that will strip out the metadata/cell execution counts, it's okay if you keep the outputs.

**Comment by sgugger** [comment]
Also, with the course tomorrow night, we probably won't have time to review anything with Jeremy until Thursday, so you should just merge directly for the conversion changes.

**Comment by rxwei** [comment]
Ok! Thanks

**Pull request merged**
