### PR TITLE
Updated python audio nb with augmentations incl. new SOTA "SpecAugment" technique.

### PR DESCRIPTION
**Pull request by mechamoth**
Can probably consider this a reasonably stable candidate for v1.0 of fastai_audio, feature-wise.

### CODE REVIEW

**Comment by mechamoth** [comment]
Oh yeah, and also first (non-functional!) draft of swift version.

**Comment by pcuenca** [comment]
One minor comment:
`from exp.nb_12c import *`

I cannot see `exp.nb_12c` in the branch or `master`. Either push it or maybe use `exp.nb_12a`, which does exist.

**Comment by pcuenca** [comment]
Great work, by the way! Going through it right now.

**Comment by mechamoth** [comment]
Thanks @pcuenca, done.

**Pull request merged**
