### PR TITLE
Add `FALayer.parameterKeyPaths(scalarType:)`

### PR DESCRIPTION
**Pull request by rxwei**
Add method `parameterKeyPaths(scalarType:)` under `FALayer`. Calling `model.parameterKeyPaths(scalarType: Float.self)` is equivalent to calling `model.recursivelyAllWritableKeyPaths(to: Tensor<Float>.self)`.

### CODE REVIEW

**Comment by jph00** [comment]
It looks like you accidentally deleted nearly all the 04 notebook! Can you please put it back and show a successful training with the new extension?

**Comment by rxwei** [comment]
> It looks like you accidentally deleted nearly all the 04 notebook!

Apologies. I'll revert this.

> Can you please put it back and show a successful training with the new extension?

Would you like me to show a successful training using this extension? Unfortunately I'm not seeing a training notebook that previously used `recursivelyAllWritableKeyPaths(to:)`, so I don't know what else to change. This extension is just adding a method to an existing type, so it doesn't change the behavior of any existing notebooks. If you could point me to a place where `recursivelyAllWritableKeyPaths(to:)` is used, I'll change that to use the new API and verify training.

**Comment by jph00** [comment]
> . If you could point me to a place where `recursivelyAllWritableKeyPaths(to:)` is used, I'll change that to use the new API and verify training.


See reply on forum.

**Comment by jph00** [comment]
@saeta @rxwei you guys can merge this directly whenever you think it's ready.

**Comment by rxwei** [comment]
It's better for @saeta to start a new PR since this one is old.

**Pull request closed without merging**
