### PR TITLE
Added 'data' param on model_summary - it was inherited from global scope

### PR DESCRIPTION
**Pull request by artste**
Using the exported method **model_summary(...)** outside of the notebook caused an error because the function uses a global scoped **'data'** variable.

**New signature**
```python
def model_summary(run, learn, data, find_all=False):
..
```

**New usage**
```python
model_summary(run, learn, data)
```

### CODE REVIEW

**Comment by jph00** [comment]
Could you run tools/run-after-git-clone then re-push this, so we don't have the metadata?

**Comment by artste** [comment]
Sure!

**Comment by artste** [comment]
Is this the tool? 
**tools/fastai-nbstripout -d dev_course/dl2/*ipynb**

I run it and it seems to remove the metadata.
https://docs.fast.ai/dev/develop.html

Running *tools/run-after-git-clone* didn't change my notebooks.

**Comment by jph00** [comment]
tools/run-after-git-clone calls that tool for you when you push/diff/etc, FYI.

--
 Jeremy Howard
 j@howard.fm

**Pull request merged**
